### ISSUE TITLE
FASTAPI endpoints

### ISSUE THREAD

**Issue by Serendipity2-0** [Serendipity2-0/TradeManV1#32]
# FastAPI Endpoints Module

This epic covers the implementation of the FastAPI Endpoints module, which will serve as the backend API for our trading system.

## Main Features:
1. Authentication
2. User and Admin Settings
3. Dashboard
4. Order Executor
5. Broker Endpoints (for 2-way matching)

### 1. Authentication
- [ ] Decide the authenication method for login and create a endpoint for it
- [ ] Create logout endpoint

### 2. User and Admin Settings
- [x] #35
- [x] Create endpoints for admin to manage user settings
- [x] Implement system-wide settings management
- [ ] Implement validation for all settings

### 3. Dashboard
- [ ] Create endpoint for overall portfolio summary
- [x] Create endpoint for performance metrics
- [x] Create endpoint for active strategies
- [x] Implement data aggregation for dashboard endpoints

### 4. Order Executor
- [ ] Create endpoint to place new order of a strategy(bulk order)
- [ ] Create endpoint to modify existing order
- [ ] Create endpoint to cancel order
- [ ] Create endpoint to get order status(As streamlit just PASS/FAIL)
- [ ] Implement order validation logic

### 5. Broker Endpoints (for 2-way matching)
- [ ] Create endpoint to fetch live P&L
- [ ] Create endpoint for account balance
- [ ] Create endpoint for open positions
- [ ] Create endpoint for order book
- [ ] Implement data transformation for broker-specific responses
- [ ] Implement two-way matching logic

## Additional Tasks:
- [ ] Set up FastAPI project structure
- [ ] Configure database connection (SQLAlchemy)
- [ ] Implement error handling and validation
- [ ] Set up testing framework and write tests
- [ ] Create API documentation (Swagger UI)
- [ ] Plan and implement deployment strategy

## Acceptance Criteria:
1. All endpoints are properly authenticated and authorized
2. User and admin can manage settings effectively
3. Dashboard endpoints provide accurate and timely data
4. Order execution is reliable and provides appropriate feedback
5. Broker endpoints accurately reflect the state of trades and account
6. Two-way matching successfully reconciles internal and broker data
7. API is well-documented, secure, and performs efficiently under load

## Related Issues:
(To be linked as they are created)

**Comment by amolkittur** [comment]
Created all the necessary endpoints for the website to be up and running.
If any requirements come up in the future we will add it in the phase 3 enhancement documents.
