### ISSUE TITLE
Refactor FastAPI endpoints

### ISSUE THREAD

**Issue by amolkittur** [Serendipity2-0/TradeManV1#40]
Here are the current endpoints 

1. GET /swagger
   - Description: Displays the Swagger UI for API documentation.

2. POST /v1/user/login
   - Description: Authenticates a user and returns a trader number if successful.

3. POST /v1/user/register
   - Description: Registers a new user with the provided details.
   - Schemas: Accounts,Active, Broker, Profile, Strategies.

4. GET /v1/user/profile-page
   - Description: Retrieves the profile information for a specific user.

5. GET /v1/user/portfolio-stats-view
   - Description: Fetches portfolio statistics for a specific user.

6. GET /v1/user/monthly-returns
   - Description: Retrieves paginated monthly returns data for a user.

7. GET /v1/user/weekly-cummulative-returns
   - Description: Fetches paginated weekly cumulative returns data for a user.

8. GET /v1/user/individual-strategy-data
   - Description: Retrieves paginated data for a specific strategy of a user.

9. GET /v1/user/strategy-graph-data
   - Description: Fetches graph data for a specific strategy of a user.

10. GET /v1/user/strategy-statistics
    - Description: Retrieves statistics for a specific strategy of a user.

11. GET /v1/user/user-broker-transactions
    - Description: Fetches paginated broker transactions data for a user, with optional date filtering.

12. GET /v1/user/users-strategy
    - Description: Retrieves a list of strategies associated with a user.

13. GET /v1/user/users-holdings
    - Description: Fetches the holdings (equity or other modes) for a user.

14. GET /v1/user/strategy-params/{strategy_name}
    - Description: Retrieves the current parameters for a specific strategy.

15. PUT /v1/user/strategy-params/{strategy_name}/{section}
    - Description: Updates parameters for a specific section of a strategy.

16. PUT /v1/admin/market-info-params
    - Description: Updates market information parameters.

17. GET /v1/admin/market-info-params
    - Description: Retrieves current market information parameters.

18. PUT /v1/admin/strategy-qty-amplifier
    - Description: Updates the StrategyQtyAmplifier for a specific strategy or all strategies.

19. GET /v1/admin/user-strategy-risk-params
    - Description: Fetches strategy risk parameters for one or multiple users.

20. PUT /v1/admin/user-strategy-risk-params
    - Description: Modifies strategy risk parameters for one or multiple users.

These endpoints cover a range of functionalities including user authentication, profile management, portfolio and strategy data retrieval, transaction history, and various administrative tasks related to market information and risk management.

#### Changes Made
**Description:** Registers a new user with the provided details.

**Schemas:** Includes sub-endpoints for Accounts, Active, Broker, Profile, and Strategies to allow for modular data submission. Each section can be submitted independently, stored temporarily, and then merged upon final registration.

#### New Endpoints:
- **POST `/register/accounts`**: Temporarily stores account details for the user.
- **POST `/register/active`**: Temporarily stores active status for the user.
- **POST `/register/broker`**: Temporarily stores broker details for the user.
- **POST `/register/profile`**: Temporarily stores profile details for the user.
- **POST `/register/strategies`**: Temporarily stores strategy details for the user.
- **POST `/register`**: Merges and registers all provided user data into a final user profile upon completion of data submission.

**Comment by amolkittur** [comment]
### Task Assignments

#### @VarshitaTP 
**Objective:** Write comprehensive test cases for the newly implemented endpoints.

**Details:**
- Please focus on ensuring that each new endpoint (listed below) is covered with both positive and negative test cases.
  - `POST /register/accounts`
  - `POST /register/active`
  - `POST /register/broker`
  - `POST /register/profile`
  - `POST /register/strategies`
  - `POST /register`
- Ensure test cases validate the expected success scenarios as well as error handling (e.g., missing required fields, incorrect formats).
- Document any edge cases you identify and include them in your tests.

#### @Anand-ak7 
**Objective:** Review and update documentation and configurations based on the recent changes in the endpoints.

**Details:**
- Review the newly added endpoint details and update the API documentation to reflect these changes accurately.
- Check if the existing documentation needs any updates due to these endpoint changes, especially check for any dependencies on old endpoints.
- Please coordinate with @VarshitaTP to ensure that any findings from testing that impact the documentation are communicated and updated promptly.

**Comment by amolkittur** [comment]
I've updated the **accounts schema** according to the required format. The changes are now reflected in the latest commit.

Please review the updates at your earliest convenience. Let me know if there are any issues or further modifications needed.

Thanks!

---

🔄 **Updated Files:**
- `User/UserApi/schemas.py`

**Comment by amolkittur** [comment]
@Anand-ak7 
I have created a new endpoint to fetch the user_id from the admin collection from firebase.

Also we need to pass the user_id in the endpoints releated to registering the user.

Please go through it and let me know if any changes are to be made.

**Comment by amolkittur** [comment]
@VarshitaTP 
While Onboarding the clients the portfolio values are being uploaded with out the date.
Make sure that the values are updated along with the dates.

**Comment by Serendipity2-0** [comment]
@amolkittur Any tasks pending in this issue? If not please close it

**Comment by amolkittur** [comment]
Closing this sub-issue:

All the endpoints are working as expected and we can close this issue now.

Resolution:
- [x] Endpoints functionality verified

Enhancement
- Write unit tests for the functions

Closing as resolved.
