### ISSUE TITLE
Endpoints for admin/profile pages

### ISSUE THREAD

**Issue by amolkittur** [Serendipity2-0/TradeManV1#45]
Endpoints for profile pages
- [ ] Endpoints for admin/profile pages(list of users, json of the user and update it.

_Originally posted by @amolkittur in https://github.com/Serendipity2-0/TradeManV1/issues/42#issuecomment-2238763216_

**Comment by amolkittur** [comment]
Endpoints for Profile page 
- [x] get request to get the list of users
- [x] get request to fetch the json of the selected user
- [x] post request to push the changes to the db

**Comment by amolkittur** [comment]
@Anand-ak7 

Please confirm if the implemented changes meet the requirements. Once I receive your approval, I will close this issue.

**Comment by Anand-ak7** [comment]
@amolkittur
Modify the GET request endpoint /v1/admin/user-details-username to use tr_no instead of a username for fetching user data. Also, update the POST request endpoint to use tr_no instead of user_details to update user details.

**Comment by amolkittur** [comment]
@Anand-ak7 
I have made the changes as requested. 
Please confirm if the implemented changes meet the requirements.

**Comment by Anand-ak7** [comment]
@amolkittur 
not able to get the user list in this **/v1/admin/user-list** endpoint

**Comment by amolkittur** [comment]
@Anand-ak7 

I have made the changes and pushed the code.
If the dict of the user does not have the field Profile we will get the error along the message which includes the trader number.

**Comment by Anand-ak7** [comment]
@amolkittur  
Need to retrieve the User Name and ID from the database response in the admin user list endpoint.
**/v1/admin/user-list**

### Example:

{
  "name": "Anand",
  "tr_no": "Tr00"
}

**Comment by amolkittur** [comment]
@Anand-ak7 
I have made the changes. Let me know if the changes work.

**Comment by amolkittur** [comment]
Closing this issue as all the tasks required to pass the Phase 1 are complete
