### ISSUE TITLE
User profile page UI - Admin dashboard

### ISSUE THREAD

**Issue by Anand-ak7** [Serendipity2-0/TradeManV1#52]
- [x] Create a UI component to display the user name list inside the profile page.
- [x] Create a UI component to show user data and update the user data.
- [x] API integration for list user name in the user profile. 
- [x] API integration for get request fetch user data. 
- [x] API integration to update the user details.

**Comment by Anand-ak7** [comment]
![Image](https://github.com/user-attachments/assets/32d3680f-ee35-4cad-9032-2e83a4e058c9)
![Image](https://github.com/user-attachments/assets/f4141ac7-fb8c-41a2-9279-4a61bcc9e474)

**Comment by amolkittur** [comment]
@Anand-ak7 
Where will you display the drop down menu to select the user and the section where i want to do the changes ?

From next issue, create in the Issue in the TradeManV1React repository and link it here. Dont create the issue in the backend repo. It will be confusing.

**Comment by Anand-ak7** [comment]
Dropdown will be bottom of the update user profile heading.

**Comment by Anand-ak7** [comment]
1. Completed with the get request API integration to fetch the user portfolio data.
2. Completed with the get request API integration to fetch the user profile data and integrated with post request api to update the user profile.

**Comment by Anand-ak7** [comment]
![Image](https://github.com/user-attachments/assets/17133e15-fbf8-4ac5-9a85-0b219fd0037c)



![Image](https://github.com/user-attachments/assets/b212c23a-1a33-4a11-9082-12ef19aeba33)



![Image](https://github.com/user-attachments/assets/69b44d1b-1a65-4275-a993-11574dbd07a2)



![Image](https://github.com/user-attachments/assets/a105627b-4298-4278-bf65-d38de011232e)



![Image](https://github.com/user-attachments/assets/dadd7726-d10e-4055-a82d-ea25deb2ae24)

**Comment by Anand-ak7** [comment]
1. Completed with the integration to fetch the user holding in the user portfolio in the admin dashboard.
2. Created update strategy component ui and integrated with the get and update request.

**Comment by Anand-ak7** [comment]
@amolkittur 

Please test the user profile UI page in the admin dashboard. If there are any UI or API response changes, please inform me the changes.

**Comment by amolkittur** [comment]
@Anand-ak7 
Merge the Userprofile section and UserPortfolio section.
You can redirect to the Userprofile section when the user enters the Userportfolio section

**Comment by amolkittur** [comment]
@Anand-ak7 
Also display only the selected segments in the sidebar for that user

**Comment by Anand-ak7** [comment]
1. Merged the user profile and user portfolio section in the admin dashboard sidebar. 
2. Added Success and failure messages for updating the user from the admin dashboard.
3. Added an alert box to update the user status in the user profile.
4. Show the segment in the sidebar according to the getting response.
