### ISSUE TITLE
DDPT setup , Onboard , Communication Messages , Enhancement story of trademain.ai #30

### ISSUE THREAD

**Issue by Serendipity2-0** [Serendipity2-0/TradeManV1#53]
- [x] create DDPI for all Trader.
- [x] onboard allTraders
- [x] Step by step telegram Message Formats to send our clients. Goal : Effective communication (This is available under main story #30)
- [x] Build enhancement story for trademan.ai(This is available under main story #62 )

- [x] Send manual telegram message to Clients until gets automated

**Comment by VarshitaTP** [comment]
**Demat Debit and Pledge Instruction(DDPI)**

Done✅

**STEP1-DDPI form courier to clients address for signature**
1.Nootana trader
2.sridhar trader
3.gayathri trader
4.venkatesh trader
5.Omkar trader
6.Amol (office)
7.Arjun(office)
8.Karthik(office)
9.Vinod trader
10.Abhishek trader
11.Anand(Office)
12.Nikhil(Office)
13.Varshita(Office)
14.Abhishek(Office)
15.Arjun trader [PENDING/ EMAIL ISSUE]
16.Sachin trader
17.srijan (office)
18.sathyarth(Office)
19.samarth(Office)
20.snowi(Office)
21.Mahaveer(office)
22.Murali(office)
23.Roshan(office)
24.vinay trader
25.Brijesh trader
26.Roopesh/nagalakshmi trader
27.pradeep hemadri
28.akash(office)
29.chinmay(office)
30.suraj(office)
31.mamatha(office)



**STEP2-DDPI form courier to FIRSTOCK ofiice**
1.Nootana trader
2.Sridhar trader
3.gayathri trader
4.venkatesh trader
5.Omkar trader
6.Amol (office)
7.Arjun(office)
8.Karthik(office)
9.Vinod trader
10.Abhishek trader
11.Anand(Office)
12.Nikhil(Office)
13.Varshita(Office)
14.Abhishek(Office)
15.Arjun trader [PENDING/ EMAIL ISSUE]
16.Sachin trader
17.srijan (office)
18.sathyarth(Office)
19.samarth(Office)
20.snowi(Office)
21.Mahaveer(office)
22.Murali(office)
23.Roshan(office)
24.vinay trader
25.Brijesh trader
26.Roopesh/nagalakshmi trader
27.pradeep hemadri
28.akash(office)
29.chinmay(office)
30.suraj(office)
31.mamatha(office)



**STEP3-DDPI SETUP COMPLETED**
1.Nootana trader
2.Sridhar trader
3.gayathri trader
4.venkatesh trader
5.Omkar trader
6.Amol (office)
7.Arjun(office)
8.Karthik(office)
9.Vinod trader
10.Abhishek trader
11.Anand(Office)
12.Nikhil(Office)
13.Varshita(Office)
14.Abhishek(Office)
15.
16.Sachin trader
17.
18.
19.
20.
21.
22.
23.
24.
25.
26.
27.
28.
29.
30.suraj(office)
31.

**Comment by VarshitaTP** [comment]
**ONBOARD CLIENTS**(trademan.ai)

Done✅

1.Nootana trader[Funds added]
2.
3.gayathri trader[Funds added] 
4.venkatesh trader[Funds added]
5.Omkar trader
6.
7.Arjun(office)[Funds added]
8.Karthik(office)[Funds added]
9.
10.
11.Anand(Office)[Funds added]
12.Nikhil(Office)[Funds added]
13.Varshita(Office)[Funds added]
14.Abhishek(Office)[Funds added]
15.
16.
17.
18.
19.
20.
21.
22.
23.
24.
25.
26.
27.
28.
29.
30.suraj(office)[Funds added] #onboardpending
31.

**Comment by VarshitaTP** [comment]
**List of Clients to send manual telegram messages in all steps to keep them updated regarding our TRADEMAN activities**

1.Nootana trader

**Comment by VarshitaTP** [comment]
Closing the issue as the DDPI can be tracked from onboardcalendar and ClientsCurrentStatus excel
