### ISSUE TITLE
Order Executor endpoints

### ISSUE THREAD

**Issue by amolkittur** [Serendipity2-0/TradeManV1#64]
#63

# Order Executor endpoint work flow

## Overview
Implement the order executor endpoint to place orders from the UI. This can be used to place new orders or repair the orders.

### 1. Strategy Selection
- Create a dropdown menu populated with all active strategies from Firebase.

### 2. User Selection
- Implement a dropdown menu showing users who have opted for the strategy selected in step 1.

### 3. Order Mode Selection
- Add a dropdown menu for selecting the order mode:
  - Repair Order
  - Complete Order

#### 3.1.1 Equity Segment
If the selected strategy is in the Equity segment:
- Input field for instrument name or stock name
- Dropdown menu for quantity selection:
  - Option to input quantity manually
  - Option to calculate quantity at the backend
- Input field for Trade ID

#### 3.1.2 Derivative Segment
If the selected strategy is in the Derivative segment:
- Input fields for:
  - Base symbol
  - Strike price
  - Option type
  - Expiry
- Dropdown menu for quantity selection:
  - Option to input quantity manually
  - Option to calculate quantity at the backend
-  Input field for Trade ID

#### 3.2.1 Equity Segment
If the selected strategy is in the Equity segment:
- Fetch stock name:
  - From Firebase's today's order if strategy has executed
  - Re-run strategy if not yet executed
- Dropdown menu for quantity selection:
  - Option to input quantity manually
  - Option to calculate quantity at the backend
-  Input field for Trade ID

#### 3.2.2 Derivative Segment
If the selected strategy is in the Derivative segment:
- Fetch strike price:
  - From Firebase's today's order if strategy has executed
  - Re-run strategy if not yet executed
- Place orders for all legs:
  - Hedge order
  - Main order
  - Stop loss
- Dropdown menu for quantity selection:
  - Option to input quantity manually
  - Option to calculate quantity at the backend
- Input field for Trade ID

## Additional Notes
- Ensure proper error handling and validation for all inputs
- Implement clear user feedback for each action
- Consider adding tooltips or help text for complex options

**Comment by Anand-ak7** [comment]
@amolkittur 
1. need to change the end point name for the admin qty calculation mode 
2. In fetch user for strategy end point list only the Tr_ No.

**Comment by Anand-ak7** [comment]
@amolkittur 

Need add order mode parameter in this post request end point
/v1/admin/place-complete-order

**Comment by amolkittur** [comment]
@Anand-ak7 

I have created 2 separate endpoints for complete order and repair order so no need of passing the order_mode as a parameter to these functions
