### ISSUE TITLE
SSL certification for backend server

### ISSUE THREAD

**Issue by VarshitaTP** [Serendipity2-0/TradeManV1#85]
```
SSL Certificate Integration for Docker Container
================================================

Current Status
--------------
We have successfully built a Docker image for our application, but we need to properly integrate SSL certificates and ensure the application is securely accessible via HTTPS.
We can access the sub domain via HTTP with port number

Steps Completed
---------------
1. Dockerfile has been created and successfully builds the image.
2. `start_docker.sh` script has been created to manage container lifecycle.
3. SSL certificates have been obtained and are located on the host machine.

Next Steps
----------
1. Verify SSL certificate path on the host machine:
   - Ensure certificates are in `/etc/letsencrypt/live/dev-api.trademan.ai/`
   - If not, update `SSL_CERT_PATH` in `start_docker.sh`

2. Run the container:
   ```bash
   chmod +x start_docker.sh
   ./start_docker.sh
   ```

3. Verify container is running:
   ```bash
   docker ps
   ```

4. Check container logs:
   ```bash
   docker logs master-container
   ```

Expected Outcome
----------------
- Container should be running and accessible via HTTPS on port 443.
- Accessing https://dev-api.trademan.ai should reach the application.

Additional Tasks
----------------
- [ ] Ensure domain dev-api.trademan.ai points to the server's IP address.
- [ ] Verify server firewall allows incoming traffic on port 443.
- [ ] Set up a process for automatic SSL certificate renewal.
- [ ] Implement monitoring for the Docker container.

Questions
---------
1. Is the SSL certificate being correctly recognized by browsers?

Notes
-----
- Remember to rebuild the Docker image and restart the container after any code changes.
- Consider implementing Docker Compose for easier management if the application grows more complex.

**Comment by Serendipity2-0** [comment]
As discussed we are removing the SSL ceritifcation for front end as well as backend.
The structure is ready and is working as expected except the reading and writing the db part.
We will implement this by creating a main story for this and design a architecture for this
